### PR TITLE
Support Swift Package Manager

### PR DESCRIPTION
**Pull request by cezres**
### Dependencies
`brew install libsodium`

### CODE REVIEW

**Comment by ashchan** [comment]
Nice. Please investigate why CI is failing.

**Comment by cezres** [comment]
@ashchan 

> The build failed. This is a change from the previous build, which passed.

**Comment by ashchan** [comment]
> @ashchan
> 
> > The build failed. This is a change from the previous build, which passed.

I didn't quite follow. The CI build on this PR still fails.

**Comment by cezres** [comment]
> > @ashchan
> > > The build failed. This is a change from the previous build, which passed.
> 
> I didn't quite follow. The CI build on this PR still fails.

Okay, I'll investigate.

**Comment by ashchan** [comment]
Seems passing now. Will review soon. Thanks!

**Comment by cezres** [comment]
After the rerun, it succeeded.

**Pull request merged**
